<?php


namespace Soroush\Action;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;

class  ActionBladeServiceProvider extends ServiceProvider
{


    public function register()
    {
        //   parent::register(); // TODO: Change the autogenerated stub
    }


    public function boot()
    {
        Blade::directive('action', function ($expression) {
            return "<?php \Action::action($expression) ?>";
        });
    }

}
